hrana client
libsql/hrana-client-rs pull request #1
Opened 2023-03-27 08:37 UTC by MarinPostma

implement hrana client

2023-03-27 10:58 UTC, merged

2023-03-27 11:46 UTC, honzasp requested changes
This looks nice! I have only a few comments and a couple of nitpicks.

However, I think we should introduce a function for sending requests, instead of repeating the code for sending a request over and over (as elaborated in a comment).

2023-03-27 11:46 UTC, honzasp commented on src/client.rs
> +    conn_sender: mpsc::UnboundedSender<Op>,
Would it make sense to use a bounded sender to provide backpressure?

2023-03-27 11:46 UTC, honzasp commented on src/conn.rs
> +    id_allocator: IdAllocator,
Perhaps we should use separate allocators for stream ids and request ids?

2023-03-27 11:46 UTC, honzasp commented on src/conn.rs
> +    async fn send_client_message(&mut self, req: &ClientMsg) -> Result<()> {
Nitpick: in a client, the only type of message that we can send is a client message, so we can name this method simply `send_message()`.

2023-03-27 11:46 UTC, honzasp commented on src/conn.rs
> +                                        let _ = waiter.send(Ok(()));
I recommend specifying the type that we are ignoring when `send()`-ing on a channel, such as:
```
let _: Result<_> = waiter.send(...);
```

It has happened to me multiple times that I accidentally dropped a `Future<Output = Result<...>>` (when sending on a bounded channel, for example) instead of `Result<...>`, which leads to very confusing bugs. Specifying the type will turn this mistake into a compile error.

2023-03-27 11:46 UTC, honzasp commented on src/conn.rs
> +            _ => return Err(Error::InvalidServerMessage),
The client should also handle `Ping` message (by replying with a `Pong`) and ignore `Pong` messages.

2023-03-27 11:46 UTC, honzasp commented on src/error.rs
> +pub enum Error {
We should add `#[non_exhaustive]` to this enum, so that we can add new variants without breaking backward compatibility.

2023-03-27 11:46 UTC, honzasp commented on src/id_alloc.rs
> +}
This seems to use the same algorithm as hrana-client-ts. It is quite nontrivial, so I would suggest also copying the comment that describes how this data structure works.

2023-03-27 11:46 UTC, honzasp commented on src/op.rs
> +    },
Nitpick: we should use the same ordering of `stream_id` and `ret` in all variants. I would suggest to always put `stream_id` first and `ret` last, with other arguments in between, but the particular order is less important than using the same order everywhere.

2023-03-28 07:42 UTC, MarinPostma commented on src/conn.rs
> +    id_allocator: IdAllocator,
I think having only one prevents stupid mistakes like allocating on one and freeing on the other, it's quite easy to get confused since they're both i32

2023-03-28 07:42 UTC, MarinPostma commented on src/error.rs
> +    WebSocket(String),
resolved in another PR

2023-03-28 07:43 UTC, MarinPostma commented on src/conn.rs
> +    }
fixed in #3

2023-03-28 07:43 UTC, MarinPostma commented on src/conn.rs
> +        if ret.send(stream_id).is_ok() {
fixed in #2

2023-03-28 07:44 UTC, MarinPostma commented on src/error.rs
> +    WebSocket(String),
This is because we fanout the error to pending requests on client exit, and this requires the error to be `Clone`

2023-03-28 07:51 UTC, honzasp commented on src/conn.rs
> +    id_allocator: IdAllocator,
By separating the allocators, these kinds of stupid mistakes would be caught: if you allocated an id on `stream_id_alloc` and deallocated it on `request_id_alloc`, you would get a panic.

2023-03-28 07:52 UTC, honzasp commented on src/error.rs
> +    WebSocket(String),
This could be solved by storing an `Arc<tungstenite::Error>`.

2023-03-28 09:08 UTC, honzasp commented on src/conn.rs
> +    id_allocator: IdAllocator,
If you try to free the same id twice, you will get a panic.